/**
 * 06 — Service Worker mode demo (client script).
 *
 * Runs createSandbox({ mode: 'service-worker' }) for real, in a real
 * browser -- registers the Service Worker generated by
 * makeServiceWorkerSource() (served live by serve.mjs at
 * /andbox-sw.js), defines two in-memory pages under /virtual/, and points
 * an iframe at one of them to prove real HTTP-shaped navigation into
 * in-memory content: no blob: URL, no content rewriting -- a normal
 * `<iframe src>` that happens to be intercepted.
 *
 * Ordering matters here, and it's not incidental: the iframe is not
 * created/navigated until createSandbox()'s returned promise resolves
 * (i.e. the registration is active). Per the doc comment on
 * makeServiceWorkerSource() (src/service-worker-source.mjs) and
 * createServiceWorkerSandbox() (src/sandbox.mjs), that ordering -- not
 * clients.claim() alone, and not any reload trick -- is what avoids the
 * "Service Worker doesn't control the first navigation" gotcha from
 * andbox#14: the iframe's first-ever request into /virtual/ happens after
 * activation, when the registration already matches that scope, so it's
 * intercepted from the very first byte.
 *
 * Isolation note, matching README's Security model framing: this demo
 * runs same-origin, for clarity. It does NOT claim same-origin
 * `service-worker` mode isolates anything from the host page -- served
 * content can see and touch this origin exactly like any other same-
 * origin page. Real isolation for untrusted content needs this mode
 * pointed at a genuinely separate origin (see README).
 */
import { createSandbox } from '../../src/index.mjs';

const statusEl = document.getElementById('status');
const logEl = document.getElementById('log');
const frameEl = document.getElementById('frame');
const passthroughBtn = document.getElementById('check-passthrough');
const passthroughLog = document.getElementById('passthrough-log');

function log(msg) {
  logEl.textContent += `${msg}\n`;
  console.log('[andbox demo]', msg);
}

async function main() {
  if (!('serviceWorker' in navigator)) {
    statusEl.textContent = 'unsupported (no navigator.serviceWorker in this browser)';
    return;
  }

  statusEl.textContent = 'registering...';
  const sw = await createSandbox({
    mode: 'service-worker',
    scriptURL: '/andbox-sw.js',
    scope: '/virtual/',
    files: {
      '/virtual/hello.html': {
        body:
          '<h1>Hello from an in-memory file</h1>' +
          '<p>No server round trip for this page -- served by the andbox ' +
          'Service Worker straight from a JS file map.</p>',
        contentType: 'text/html',
      },
      '/virtual/about.html': {
        body:
          '<h1>About</h1>' +
          '<p>Also served from the same file map, proving multi-path ' +
          'routing works, not just one lucky path.</p>',
        contentType: 'text/html',
      },
    },
  });
  log(`registered, scope: ${sw.scope}`);
  statusEl.textContent = 'active';

  // Only now, with the registration active, does the iframe make its
  // very first request into /virtual/ -- see the module doc comment above.
  frameEl.src = '/virtual/hello.html';

  passthroughBtn.addEventListener('click', async () => {
    const res = await fetch('/virtual/does-not-exist.html');
    const body = await res.text();
    passthroughLog.textContent =
      `GET /virtual/does-not-exist.html -> ${res.status}\n${body}\n\n` +
      "(This is the real dev server's 404, proving the Service Worker " +
      'fell through to the network instead of swallowing the request.)';
  });

  // Exposed for manual poking in devtools, not used by the demo itself.
  window.__andboxDemo = { sw };
}

main().catch((e) => {
  statusEl.textContent = 'error';
  log(String((e && e.stack) || e));
});
